version: "3"

tasks:
  default:
    desc: "Show available tasks"
    cmds:
      - task --list-all
  encrypt-caesar:
    desc: "Run encrypt/decrypt application with Caesar cipher"
    cmds:
      - go run ./cmd/cryptoalgo/main.go -cipher=caesar
  encrypt-gamma:
    desc: "Run encrypt/decrypt application with Gamma cipher"
    cmds:
      - go run ./cmd/cryptoalgo/ -cipher gamma
  encrypt-rearrangement:
    desc: "Run encrypt/decrypt application with rearrangement cipher"
    cmds:
      - go run ./cmd/cryptoalgo/ -cipher rearrangement
  sign:
    desc: "Run sign application"
    cmds:
      - go run ./cmd/sign/
  test:
    cmds:
      - go test ./... -v
  update:mod:
    desc: "Update go mod"
    cmds:
      - go get -u ./...
  tidy:mod:
    desc: "Tidy go mod"
    cmds:
      - go mod tidy
  godoc:
    desc: "Host a Godoc web server on the http://localhost:6060/pkg/github.com/hrvadl/converter?m=all"
    deps: [install:godoc]
    cmds:
      - echo "go to the http://localhost:6060/pkg/github.com/hrvadl/converter?m=all"
      - godoc -http=:6060
  install:godoc:
    desc: "Installed godoc util"
    cmds:
      - go install -v golang.org/x/tools/cmd/godoc@latest
    status:
      - command godoc -h
